version: '3.9'

services:
    php:
        image: php:8.1.4-fpm-alpine3.14
        volumes:
            - ./app:/var/www/html

    nginx:
        image: nginx:1.21.6-alpine
        volumes:
            - ./app:/var/www/html
            - .docker/nginx:/etc/nginx/conf.d
        ports:
            - 80:80
        networks:
            default:
                aliases:
                    - ${DOMAIN_ALIAS}

    mysql:
        image: mysql:8.0.28-debian
        volumes:
            - .docker/data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
